### ISSUE TITLE
Release 0.9.5 broke existing gitversion tasks

### ISSUE THREAD

**Issue by quasarea** [GitTools/actions#245] opened 2020-11-09 11:39 UTC
Related to https://github.com/GitTools/GitVersion/issues/2434

Arguments that were happy running on 0.9.4 are now broken on 0.9.5:
```
Starting: GitVersion Config
==============================================================================
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
Version      : 0.9.4
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
Command: dotnet-gitversion C:/agent/_work/46/s /output json /output buildserver /config C:\agent\_work\46\s\Templates\ComponentVersioning\GitVersion.yml /targetpath C:\agent\_work\46\s\Source /showconfig
C:\agent\_work\_tool\GitVersion.Tool\5.3.7\x64\dotnet-gitversion.exe C:/agent/_work/46/s /output json /output buildserver /config C:\agent\_work\46\s\Templates\ComponentVersioning\GitVersion.yml /targetpath C:\agent\_work\46\s\Source /showconfig
INFO [10/23/20 12:11:21:12] Working directory: C:\agent\_work\46\s\Source
assembly-versioning-scheme: Major
```
now:
```
Starting: GitVersion Config
==============================================================================
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
Version      : 0.9.5
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
Command: dotnet-gitversion C:/agent/_work/46/s /output json /output buildserver /config C:\agent\_work\46\s\Templates\ComponentVersioning\GitVersion.yml /targetpath C:\agent\_work\46\s\Source /showconfig
C:\agent\_work\_tool\GitVersion.Tool\5.5.0\x64\dotnet-gitversion.exe C:/agent/_work/46/s /output json /output buildserver /config C:\agent\_work\46\s\Templates\ComponentVersioning\GitVersion.yml "/targetpath C:\agent\_work\46\s\Source /showconfig"

Unhandled Exception: GitVersion.WarningException: Could not parse command line parameter '/targetpath C:\agent\_work\46\s\Source /showconfig'.
   at GitVersion.ArgumentParser.ParseTargetPath(Arguments arguments, String name, String[] values, String value, Boolean parseEnded) in D:\a\GitVersion\GitVersion\src\GitVersionExe\ArgumentParser.cs:line 194
   at GitVersion.ArgumentParser.ParseSwitchArguments(Arguments arguments, NameValueCollection switchesAndValues, Int32 i) in D:\a\GitVersion\GitVersion\src\GitVersionExe\ArgumentParser.cs:line 126
   at GitVersion.ArgumentParser.ParseArguments(String[] commandLineArguments) in D:\a\GitVersion\GitVersion\src\GitVersionExe\ArgumentParser.cs:line 88
```

**Comment by quasarea** [comment] 2020-11-09 11:53
btw, are you testing new targets before releasing it?

As far as I see you don't version your task so we cannot fall back to last working version.:
![image](https://user-images.githubusercontent.com/10334982/98537973-fca92080-2281-11eb-9c95-e0ecb884488b.png)

**Comment by Leosori** [comment] 2020-11-09 13:02
The problem is caused by the enclosing quotation marks for the additional GitVersion arguments
GitVersion treats the additional arguments as one parameter and fails parsing them

Please fix this ASAP. All of our builds are currently failing

**Comment by adhodgson1** [comment] 2020-11-09 14:49
In my case the additionalArguments: '/output file' failed, a temporary workaround which works in my case since I don't need to provide any other parameters is to use additionalArguments: 'file' which works as a continuation of the tool's existing default arguments. This caused hell this morning as this template is used as the basis for most of our pipelines.

**Comment by quasarea** [comment] 2020-11-09 15:25
Ok, workaround for now is to target older version, I was wrong that they don't publish it, it's just azure is not listing it there.

I found it listed at https://github.com/marketplace/actions/use-actions?version=v0.9.4

So, just update your calls to specific version:
```
  - task: gitversion/execute@0.9.4
...
```

**Comment by Leosori** [comment] 2020-11-09 18:47
This workaround seems to work only for the YAML pipelines. I could not find a way to specify the version in the classic pipeline.

The problem from with those additional quotes was fixed with the previous 0.94 release, see bug #136  and PR #145

**Comment by quasarea** [comment] 2020-11-10 09:34
Nope unfortunately havent found anything for classic, I think we need to submit bug with task version dropdown not listening versions available at marketplace, but not sure where yet :)

**Comment by adhodgson1** [comment] 2020-11-10 09:57
FWIW I haven't had any luck in pinning the version in Azure Devops using YAML pipelines, it was the first thing I really tried to do. In the Azure Devops organization settings I could only see a few versions that were deployed automatically over the weekend. Specifying those versions in the pipeline gave me an object reference not set to an instance of an object error.

**Comment by arturcic** [comment] 2020-11-10 10:47
> This workaround seems to work only for the YAML pipelines. I could not find a way to specify the version in the classic pipeline.
> 
> The problem from with those additional quotes was fixed with the previous 0.94 release, see bug #136 and PR #145

I think the issue is caused by that PR. Even if the fix was "included" in v0.9.4 it was not compiled, that means it as working as before the fix. 

I guess I will have to undo the changes from that PR and release 0.9.6 but with compiled dist files. Thoughts?

**Comment by Leosori** [comment] 2020-11-10 14:16
hmm, you are correct. The fix was not compiled to JavaScript for 0.94. But then I have no idea how this even worked with the previous version.

We started using this extension with version 0.94. Can't tell if version 0.93 was behaving in the same way.

I tried to dig into the code, but I'm mainly a C# developer, so I may not know all the quirks involved with TypeScript and JavaScript. Basically we have an string array of arguments and we are adding the additional arguments at the end.
_additionalArguments_ is a string returned by getInput, e.g. "/someParameter someValue /anotherSwitch"
Because _additionalArgument_ is a string and not an array, pushing it to the arguments array results in

["/output", "json", "/output", "buildserver", "/someParameter someValue /anotherSwitch"]

Passing this via the args() method to the tool runner will wrap the last parameter in quotes because it contains spaces. This is the expected behavior of the tool runner class. So splitting the _additionalArguments_ string before pushing it to the array should prevent this. But it was not compiled with version 0.94 and yet it did somehow work?!

As you can see in the log line starting with "Command:", the array itself does not contain any quotes so far. They are added by the tool runner. Maybe instead of trying to fix the array, simple pass the line that was created for the Command log line?

The tool runner class offers a line() method that will accept a single string and handle the parsing of quotes, spaces and so on. This should also handle cases where the _additionalArguments_ string contains quotes, e.g. '/someParam "value with spaces" /switch'
https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/azure-pipelines-task-lib.md#toolrunnerToolRunnerarg

**Comment by arturcic** [comment] 2020-11-10 14:55
@Leosori that was an interesting explanation, thank you for the investigation. Do you think you could send us a PR with the suggestion?

**Comment by Leosori** [comment] 2020-11-10 20:05
@arturcic I have created PR #249

**Closed** 2020-11-11 13:51 UTC

**Comment by arturcic** [comment] 2020-11-11 13:55
@GSDragoon do you mind checking if it works with the master version?

**Comment by GSDragoon** [comment] 2020-11-11 18:07
Yes, my GitVersion actions worked just now targeting `master`. [link](https://github.com/GSDragoon/RadeonSoftwareSlimmer/runs/1386556304?check_suite_focus=true)

**Comment by GSDragoon** [comment] 2020-11-11 18:08
> @GSDragoon do you mind checking if it works with the master version?

Yes, my GitVersion actions worked just now targeting `master`. [link](https://github.com/GSDragoon/RadeonSoftwareSlimmer/runs/1386556304?check_suite_focus=true)

**Comment by Leosori** [comment] 2020-11-12 09:22
can confirm, 0.96 fixed the problem for us

**Comment by arturcic** [comment] 2020-11-12 09:24
@Leosori thanks for the feedback and the input
