### ISSUE TITLE
(node:2743) UnhandledPromiseRejectionWarning: TypeError: (e || "").replace is not a function

### ISSUE THREAD

**Issue by bonesoul** [GitTools/actions#77] opened 2020-03-26 11:59 UTC
when using the config;

```
    - name: install gitversion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    - name: setup gitversion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
```
getting the error;

```
2020-03-26T11:58:13.2019138Z ##[group]Run gittools/actions/gitversion/execute@v0.9.2
2020-03-26T11:58:13.2019318Z with:
2020-03-26T11:58:13.2019453Z   useConfigFile: false
2020-03-26T11:58:13.2019581Z   updateAssemblyInfo: false
2020-03-26T11:58:13.2019710Z env:
2020-03-26T11:58:13.2019832Z   DOTNET_CLI_TELEMETRY_OPTOUT: 1
2020-03-26T11:58:13.2019916Z   DOTNET_ROOT: ../share/dotnet
2020-03-26T11:58:13.2020041Z ##[endgroup]
2020-03-26T11:58:13.2672424Z Command: dotnet-gitversion /home/runner/work/hypeengine/hypeengine /output json /output buildserver
2020-03-26T11:58:13.2745258Z [command]/opt/hostedtoolcache/GitVersion.Tool/5.2.4/x64/dotnet-gitversion /home/runner/work/hypeengine/hypeengine /output json /output buildserver
2020-03-26T11:58:13.5028053Z INFO [03/26/20 11:58:13:49] Working directory: /home/runner/work/hypeengine/hypeengine
2020-03-26T11:58:13.5187217Z INFO [03/26/20 11:58:13:51] Applicable build agent found: 'GitHubActions'.
2020-03-26T11:58:13.5200042Z INFO [03/26/20 11:58:13:51] Branch from build environment: refs/heads/feature/dotnetcore-3.1.200
2020-03-26T11:58:13.5200922Z INFO [03/26/20 11:58:13:51] Begin: Normalizing git directory for branch 'refs/heads/feature/dotnetcore-3.1.200'
2020-03-26T11:58:13.5504380Z   INFO [03/26/20 11:58:13:54] One remote found (origin -> 'https://github.com/bonesoul/hypeengine').
2020-03-26T11:58:13.5530249Z   INFO [03/26/20 11:58:13:55] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
2020-03-26T11:58:13.5577501Z   INFO [03/26/20 11:58:13:55] Updating local branch refs/heads/feature/dotnetcore-3.1.200 to point at 9810146ebdd84f7b57cb3784955d1610bd816a2f
2020-03-26T11:58:13.5826230Z   INFO [03/26/20 11:58:13:58] Creating local branch from remote tracking 'refs/remotes/origin/develop'.
2020-03-26T11:58:13.5956450Z   INFO [03/26/20 11:58:13:59] Creating local branch from remote tracking 'refs/remotes/origin/feature/data-processing'.
2020-03-26T11:58:13.5977709Z   INFO [03/26/20 11:58:13:59] Creating local branch from remote tracking 'refs/remotes/origin/master'.
2020-03-26T11:58:13.5999463Z   INFO [03/26/20 11:58:13:59] Creating local branch from remote tracking 'refs/remotes/origin/psn-task'.
2020-03-26T11:58:13.6008160Z   INFO [03/26/20 11:58:13:60] HEAD points at branch 'refs/heads/feature/dotnetcore-3.1.200'.
2020-03-26T11:58:13.6019407Z   INFO [03/26/20 11:58:13:60] End: Normalizing git directory for branch 'refs/heads/feature/dotnetcore-3.1.200' (Took: 81.41ms)
2020-03-26T11:58:13.6019655Z   INFO [03/26/20 11:58:13:60] Project root is: /home/runner/work/hypeengine/hypeengine/
2020-03-26T11:58:13.6019919Z   INFO [03/26/20 11:58:13:60] DotGit directory is: /home/runner/work/hypeengine/hypeengine/.git
2020-03-26T11:58:13.6155557Z   INFO [03/26/20 11:58:13:61] Begin: Loading version variables from disk cache
2020-03-26T11:58:13.6164284Z     INFO [03/26/20 11:58:13:61] Cache file /home/runner/work/hypeengine/hypeengine/.git/gitversion_cache/A1AA4C4E426E17E32D916FCD5B1BE9A61A22A18B.yml not found.
2020-03-26T11:58:13.6166138Z   INFO [03/26/20 11:58:13:61] End: Loading version variables from disk cache (Took: 1.01ms)
2020-03-26T11:58:13.7040889Z   INFO [03/26/20 11:58:13:70] Using latest commit on specified branch
2020-03-26T11:58:13.7229053Z   INFO [03/26/20 11:58:13:72] Begin: Attempting to inherit branch configuration from parent branch
2020-03-26T11:58:13.7264116Z     INFO [03/26/20 11:58:13:72] Begin: Finding branch source of 'feature/dotnetcore-3.1.200'
2020-03-26T11:58:13.7383866Z       INFO [03/26/20 11:58:13:73] Begin: Finding merge base between 'feature/dotnetcore-3.1.200' and 'develop'.
2020-03-26T11:58:13.7443873Z         INFO [03/26/20 11:58:13:74] Found merge base of ad66e185673835b552220007ba82f90466c1823a
2020-03-26T11:58:13.7510237Z         INFO [03/26/20 11:58:13:75] Merge base of feature/dotnetcore-3.1.200' and 'develop is ad66e185673835b552220007ba82f90466c1823a
2020-03-26T11:58:13.7512886Z       INFO [03/26/20 11:58:13:75] End: Finding merge base between 'feature/dotnetcore-3.1.200' and 'develop'. (Took: 12.56ms)
2020-03-26T11:58:13.7514332Z       INFO [03/26/20 11:58:13:75] Begin: Finding merge base between 'feature/dotnetcore-3.1.200' and 'master'.
2020-03-26T11:58:13.7520292Z         INFO [03/26/20 11:58:13:75] Found merge base of 1c75f9da771918547c4e854759f49da95aa4f855
2020-03-26T11:58:13.7522057Z         INFO [03/26/20 11:58:13:75] Merge base of feature/dotnetcore-3.1.200' and 'master is 1c75f9da771918547c4e854759f49da95aa4f855
2020-03-26T11:58:13.7523060Z       INFO [03/26/20 11:58:13:75] End: Finding merge base between 'feature/dotnetcore-3.1.200' and 'master'. (Took: 0.78ms)
2020-03-26T11:58:13.7611018Z       INFO [03/26/20 11:58:13:76] Multiple source branches have been found, picking the first one (develop).
2020-03-26T11:58:13.7611642Z This may result in incorrect commit counting.
2020-03-26T11:58:13.7611935Z Options were:
2020-03-26T11:58:13.7612262Z develop, master
2020-03-26T11:58:13.7612984Z     INFO [03/26/20 11:58:13:76] End: Finding branch source of 'feature/dotnetcore-3.1.200' (Took: 35.03ms)
2020-03-26T11:58:13.7652325Z     INFO [03/26/20 11:58:13:76] Begin: Getting branches containing the commit 'ad66e185673835b552220007ba82f90466c1823a'.
2020-03-26T11:58:13.7652588Z       INFO [03/26/20 11:58:13:76] Trying to find direct branches.
2020-03-26T11:58:13.7652773Z       INFO [03/26/20 11:58:13:76] No direct branches found, searching through all branches.
2020-03-26T11:58:13.7653188Z       INFO [03/26/20 11:58:13:76] Searching for commits reachable from 'develop'.
2020-03-26T11:58:13.7700005Z       INFO [03/26/20 11:58:13:76] The branch 'develop' has a matching commit.
2020-03-26T11:58:13.7700917Z       INFO [03/26/20 11:58:13:76] Searching for commits reachable from 'master'.
2020-03-26T11:58:13.7740691Z       INFO [03/26/20 11:58:13:77] The branch 'master' has no matching commits.
2020-03-26T11:58:13.7741651Z       INFO [03/26/20 11:58:13:77] Searching for commits reachable from 'origin/develop'.
2020-03-26T11:58:13.7803039Z       INFO [03/26/20 11:58:13:77] The branch 'origin/develop' has a matching commit.
2020-03-26T11:58:13.7803999Z       INFO [03/26/20 11:58:13:78] Searching for commits reachable from 'origin/master'.
2020-03-26T11:58:13.7889141Z       INFO [03/26/20 11:58:13:78] The branch 'origin/master' has no matching commits.
2020-03-26T11:58:13.7889656Z     INFO [03/26/20 11:58:13:78] End: Getting branches containing the commit 'ad66e185673835b552220007ba82f90466c1823a'. (Took: 21.66ms)
2020-03-26T11:58:13.7890074Z     INFO [03/26/20 11:58:13:78] Begin: Getting branches containing the commit '9810146ebdd84f7b57cb3784955d1610bd816a2f'.
2020-03-26T11:58:13.7890275Z       INFO [03/26/20 11:58:13:78] Trying to find direct branches.
2020-03-26T11:58:13.7890505Z       INFO [03/26/20 11:58:13:78] No direct branches found, searching through all branches.
2020-03-26T11:58:13.7890896Z       INFO [03/26/20 11:58:13:78] Searching for commits reachable from 'develop'.
2020-03-26T11:58:13.7968227Z       INFO [03/26/20 11:58:13:79] The branch 'develop' has no matching commits.
2020-03-26T11:58:13.7968616Z       INFO [03/26/20 11:58:13:79] Searching for commits reachable from 'master'.
2020-03-26T11:58:13.8038370Z       INFO [03/26/20 11:58:13:80] The branch 'master' has no matching commits.
2020-03-26T11:58:13.8039076Z       INFO [03/26/20 11:58:13:80] Searching for commits reachable from 'origin/develop'.
2020-03-26T11:58:13.8112100Z       INFO [03/26/20 11:58:13:81] The branch 'origin/develop' has no matching commits.
2020-03-26T11:58:13.8112477Z       INFO [03/26/20 11:58:13:81] Searching for commits reachable from 'origin/master'.
2020-03-26T11:58:13.8181324Z       INFO [03/26/20 11:58:13:81] The branch 'origin/master' has no matching commits.
2020-03-26T11:58:13.8181892Z     INFO [03/26/20 11:58:13:81] End: Getting branches containing the commit '9810146ebdd84f7b57cb3784955d1610bd816a2f'. (Took: 31.07ms)
2020-03-26T11:58:13.8186561Z     INFO [03/26/20 11:58:13:81] Found possible parent branches: develop, origin/develop
2020-03-26T11:58:13.8197528Z     WARN [03/26/20 11:58:13:81] Failed to inherit Increment branch configuration, ended up with: develop, origin/develop
2020-03-26T11:58:13.8198095Z Falling back to develop branch config
2020-03-26T11:58:13.8206805Z   INFO [03/26/20 11:58:13:81] End: Attempting to inherit branch configuration from parent branch (Took: 97.30ms)
2020-03-26T11:58:13.8245689Z   INFO [03/26/20 11:58:13:82] Running against branch: feature/dotnetcore-3.1.200 (9810146ebdd84f7b57cb3784955d1610bd816a2f)
2020-03-26T11:58:13.8263471Z   INFO [03/26/20 11:58:13:82] Begin: Calculating base versions
2020-03-26T11:58:13.8394225Z     INFO [03/26/20 11:58:13:83] Fallback base version: 0.1.0 with commit count source b898a968417ed4eb9edddcce6c9c75c0fa0fa665 (Incremented: None)
2020-03-26T11:58:13.9612773Z     INFO [03/26/20 11:58:13:96] Git tag '0.5.1': 0.5.1 with commit count source 3713ebecda37dfd090ac4e8e3876209dde69ad51 (Incremented: 0.6.0)
2020-03-26T11:58:13.9613305Z     INFO [03/26/20 11:58:13:96] Git tag '0.5.0': 0.5.0 with commit count source cb91626f07c674a790c089d857a3351a06f03b6a (Incremented: 0.6.0)
2020-03-26T11:58:13.9615977Z     INFO [03/26/20 11:58:13:96] Git tag '0.4.3': 0.4.3 with commit count source 68922f4abe3011238e206e16b503e23236dd7b68 (Incremented: 0.5.0)
2020-03-26T11:58:13.9616692Z     INFO [03/26/20 11:58:13:96] Git tag '0.4.2': 0.4.2 with commit count source fd803f150eeffe046bfd7ce57abf534127010160 (Incremented: 0.5.0)
2020-03-26T11:58:13.9620895Z     INFO [03/26/20 11:58:13:96] Git tag '0.4.1': 0.4.1 with commit count source a67bef9a86cab61ed8b34ea14e6f76dde74eb34a (Incremented: 0.5.0)
2020-03-26T11:58:13.9722310Z     INFO [03/26/20 11:58:13:97] Git tag '0.5.1': 0.5.1 with commit count source 3713ebecda37dfd090ac4e8e3876209dde69ad51 (Incremented: 0.6.0)
2020-03-26T11:58:13.9722757Z     INFO [03/26/20 11:58:13:97] Git tag '0.5.0': 0.5.0 with commit count source cb91626f07c674a790c089d857a3351a06f03b6a (Incremented: 0.6.0)
2020-03-26T11:58:13.9726126Z     INFO [03/26/20 11:58:13:97] Git tag '0.4.3': 0.4.3 with commit count source 68922f4abe3011238e206e16b503e23236dd7b68 (Incremented: 0.5.0)
2020-03-26T11:58:13.9730264Z     INFO [03/26/20 11:58:13:97] Git tag '0.4.2': 0.4.2 with commit count source fd803f150eeffe046bfd7ce57abf534127010160 (Incremented: 0.5.0)
2020-03-26T11:58:13.9734478Z     INFO [03/26/20 11:58:13:97] Git tag '0.4.1': 0.4.1 with commit count source a67bef9a86cab61ed8b34ea14e6f76dde74eb34a (Incremented: 0.5.0)
2020-03-26T11:58:13.9793521Z     INFO [03/26/20 11:58:13:97] Found multiple base versions which will produce the same SemVer (0.6.0), taking oldest source for commit counting (Git tag '0.5.0')
2020-03-26T11:58:13.9794222Z     INFO [03/26/20 11:58:13:97] Base version used: Git tag '0.5.0': 0.5.0 with commit count source cb91626f07c674a790c089d857a3351a06f03b6a (Incremented: 0.6.0)
2020-03-26T11:58:13.9794398Z   INFO [03/26/20 11:58:13:97] End: Calculating base versions (Took: 153.07ms)
2020-03-26T11:58:13.9808214Z   INFO [03/26/20 11:58:13:98] 95 commits found between cb91626f07c674a790c089d857a3351a06f03b6a and 9810146ebdd84f7b57cb3784955d1610bd816a2f
2020-03-26T11:58:13.9821694Z   INFO [03/26/20 11:58:13:98] Using branch name to calculate version tag
2020-03-26T11:58:13.9829373Z   INFO [03/26/20 11:58:13:98] Begin: Getting version tags from branch 'refs/heads/feature/dotnetcore-3.1.200'.
2020-03-26T11:58:13.9920885Z   INFO [03/26/20 11:58:13:99] End: Getting version tags from branch 'refs/heads/feature/dotnetcore-3.1.200'. (Took: 9.09ms)
2020-03-26T11:58:13.9993854Z   INFO [03/26/20 11:58:13:99] Begin: Creating dictionary
2020-03-26T11:58:14.0045684Z   INFO [03/26/20 11:58:14:00] End: Creating dictionary (Took: 5.23ms)
2020-03-26T11:58:14.0079754Z   INFO [03/26/20 11:58:14:00] Begin: Storing version variables to cache file /home/runner/work/hypeengine/hypeengine/.git/gitversion_cache/A1AA4C4E426E17E32D916FCD5B1BE9A61A22A18B.yml
2020-03-26T11:58:14.0531064Z   INFO [03/26/20 11:58:14:05] End: Storing version variables to cache file /home/runner/work/hypeengine/hypeengine/.git/gitversion_cache/A1AA4C4E426E17E32D916FCD5B1BE9A61A22A18B.yml (Took: 44.81ms)
2020-03-26T11:58:14.0541551Z   INFO [03/26/20 11:58:14:05] Running on Unix.
2020-03-26T11:58:14.0542348Z   INFO [03/26/20 11:58:14:05] Applicable build agent found: 'GitHubActions'.
2020-03-26T11:58:14.0547368Z Executing GenerateSetVersionMessage for 'GitHubActions'.
2020-03-26T11:58:14.0547442Z 
2020-03-26T11:58:14.0547735Z Executing GenerateBuildLogOutput for 'GitHubActions'.
2020-03-26T11:58:14.0573700Z {
2020-03-26T11:58:14.0573801Z   "Major":0,
2020-03-26T11:58:14.0573933Z   "Minor":6,
2020-03-26T11:58:14.0574105Z   "Patch":0,
2020-03-26T11:58:14.0574616Z   "PreReleaseTag":"dotnetcore-3-1-200.1",
2020-03-26T11:58:14.0574893Z   "PreReleaseTagWithDash":"-dotnetcore-3-1-200.1",
2020-03-26T11:58:14.0575157Z   "PreReleaseLabel":"dotnetcore-3-1-200",
2020-03-26T11:58:14.0575296Z   "PreReleaseNumber":1,
2020-03-26T11:58:14.0575426Z   "WeightedPreReleaseNumber":30001,
2020-03-26T11:58:14.0575579Z   "BuildMetaData":95,
2020-03-26T11:58:14.0575710Z   "BuildMetaDataPadded":"0095",
2020-03-26T11:58:14.0576017Z   "FullBuildMetaData":"95.Branch.feature-dotnetcore-3.1.200.Sha.9810146ebdd84f7b57cb3784955d1610bd816a2f",
2020-03-26T11:58:14.0576219Z   "MajorMinorPatch":"0.6.0",
2020-03-26T11:58:14.0576490Z   "SemVer":"0.6.0-dotnetcore-3-1-200.1",
2020-03-26T11:58:14.0576757Z   "LegacySemVer":"0.6.0-dotnetcore-3-1-200-1",
2020-03-26T11:58:14.0577033Z   "LegacySemVerPadded":"0.6.0-dotnetcore-3-1--0001",
2020-03-26T11:58:14.0577170Z   "AssemblySemVer":"0.6.0.0",
2020-03-26T11:58:14.0577300Z   "AssemblySemFileVer":"0.6.0.0",
2020-03-26T11:58:14.0577752Z   "FullSemVer":"0.6.0-dotnetcore-3-1-200.1+95",
2020-03-26T11:58:14.0578514Z   "InformationalVersion":"0.6.0-dotnetcore-3-1-200.1+95.Branch.feature-dotnetcore-3.1.200.Sha.9810146ebdd84f7b57cb3784955d1610bd816a2f",
2020-03-26T11:58:14.0578837Z   "BranchName":"feature/dotnetcore-3.1.200",
2020-03-26T11:58:14.0579119Z   "EscapedBranchName":"feature-dotnetcore-3-1-200",
2020-03-26T11:58:14.0579221Z   "Sha":"9810146ebdd84f7b57cb3784955d1610bd816a2f",
2020-03-26T11:58:14.0579363Z   "ShortSha":9810146,
2020-03-26T11:58:14.0579792Z   "NuGetVersionV2":"0.6.0-dotnetcore-3-1--0001",
2020-03-26T11:58:14.0580059Z   "NuGetVersion":"0.6.0-dotnetcore-3-1--0001",
2020-03-26T11:58:14.0580324Z   "NuGetPreReleaseTagV2":"dotnetcore-3-1--0001",
2020-03-26T11:58:14.0580580Z   "NuGetPreReleaseTag":"dotnetcore-3-1--0001",
2020-03-26T11:58:14.0580916Z   "VersionSourceSha":"cb91626f07c674a790c089d857a3351a06f03b6a",
2020-03-26T11:58:14.0581083Z   "CommitsSinceVersionSource":95,
2020-03-26T11:58:14.0581225Z   "CommitsSinceVersionSourcePadded":"0095",
2020-03-26T11:58:14.0581666Z   "CommitDate":"2020-03-26"
2020-03-26T11:58:14.0581751Z }
2020-03-26T11:58:14.0962925Z (node:2743) UnhandledPromiseRejectionWarning: TypeError: (e || "").replace is not a function
2020-03-26T11:58:14.0963104Z     at /home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:943
2020-03-26T11:58:14.0963261Z     at s.toString (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:1005)
2020-03-26T11:58:14.0963401Z     at o (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:372)
2020-03-26T11:58:14.0963540Z     at Object.t.issue (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:432)
2020-03-26T11:58:14.0963678Z     at c (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:9:741)
2020-03-26T11:58:14.0963974Z     at Object.t.setFailed (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:9:1482)
2020-03-26T11:58:14.0964121Z     at h.setFailed (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:308:1902)
2020-03-26T11:58:14.0964260Z     at Object.<anonymous> (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:336:1575)
2020-03-26T11:58:14.0964376Z     at Generator.next (<anonymous>)
2020-03-26T11:58:14.0964687Z     at s (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:336:170)
2020-03-26T11:58:14.0965174Z (node:2743) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-03-26T11:58:14.0965871Z (node:2743) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by arturcic** [comment] 2020-03-26 12:04
I think this is a duplicate of #76

**Comment by bonesoul** [comment] 2020-03-26 12:05
yes sorry for the duplicate.

**Closed by arturcic** 2020-03-26 12:04 UTC
