### ISSUE TITLE
Mainline mode does not support prerease releases in github releases

### ISSUE THREAD

**Issue by ptr727** [GitTools/actions#271] opened 2020-11-23 21:26 UTC
Reference: 
https://github.com/GitTools/GitVersion/issues/2211
https://github.com/GitTools/GitVersion/issues/1809

The moment there is a develop/alpha/prerelease in github releases the tool fails.
This bug prevents the ability to release prerelease builds to github.
Delete the prerelease from github releases, and the tool works again.

See:
https://github.com/ptr727/PlexCleaner/blob/develop/.github/workflows/BuildPublishPipeline.yml

```
    INFO [11/23/20 13:17:14:00] Base version used: Git tag '1.12.0-alpha0003': 1.12.0-alpha.3 with commit count source ef7d358fad3f6bd91c774c127a0cf8cc759e0e7c
  INFO [11/23/20 13:17:14:00] End: Calculating base versions (Took: 437.31ms)
  ERROR [11/23/20 13:17:14:01] An unexpected error occurred:
System.NotSupportedException: Mainline development mode doesn't yet support pre-release tags on master
   at GitVersion.VersionCalculation.MainlineVersionCalculator.FindMainlineModeVersion(BaseVersion baseVersion)
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion()
   at GitVersion.GitVersionTool.CalculateVersionVariables()
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions)
```

**Comment by arturcic** [comment] 2020-11-26 06:31
I think the issue is not related to this repository, as the source of the issue is the gitversion tool. You already referenced the issue in that repository so closing this issue

**Closed by arturcic** 2020-11-26 06:31 UTC

**Comment by ptr727** [comment] 2020-11-30 03:56
Ok, but per the comment on the other issue, it will not get fixed.
So, if GitHub Actions and GitHub Releases is a supported config, and Mainline mode is a supported config, but not together, then could you help out and offer an alternative?
